In [1]:
import pandas as pd
import numpy as np

In [2]:
test_x = pd.read_csv("./data/test_x/test_x1.csv")

In [3]:
test_x.describe()

TurbID            Day           Wspd           Wdir  \
count  270144.000000  270144.000000  267641.000000  267641.000000   
mean       67.500000       7.500000       4.651799       3.452441   
std        38.681462       4.031136       3.626204      36.367664   
min         1.000000       1.000000       0.000000    -173.780000   
25%        34.000000       4.000000       1.730000      -3.590000   
50%        67.500000       7.500000       3.500000      -0.010000   
75%       101.000000      11.000000       6.710000       4.110000   
max       134.000000      14.000000      19.910000     172.080000   

                Etmp           Itmp           Ndir           Pab1  \
count  267641.000000  267641.000000  267641.000000  267641.000000   
mean       33.557435      31.150499     149.823850      33.224197   
std        56.769614      15.728790     183.377029      40.780027   
min      -272.970000    -272.970000    -592.250000      -1.990000   
25%        22.250000      27.720000      14.340000       0.010000   
50%        26.370000      31.910000     171.250000       4.450000   
75%        30.560000      36.020000     294.450000      89.680000   
max       394.040000      82.040000     616.780000      91.550000   

                Pab2           Pab3           Prtv           Patv  
count  267641.000000  267641.000000  267641.000000  267641.000000  
mean       33.209907      33.210934     -15.120064     314.209828  
std        40.761651      40.762099      44.889646     426.432552  
min        -1.990000      -1.990000    -627.640000      -7.660000  
25%         0.010000       0.010000     -30.890000      -0.300000  
50%         4.450000       4.460000      -0.300000     109.800000  
75%        89.670000      89.680000      -0.300000     484.950000  
max        91.110000      90.930000     149.290000    1560.580000

In [6]:
np.unique(test_x['Day'])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [7]:
np.unique(test_x['TurbID'])

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134])

In [4]:
test_y = pd.read_csv("./data/test_y/test_y1.csv")

In [5]:
test_y.describe()

TurbID           Day          Wspd          Wdir          Etmp  \
count  38592.000000  38592.000000  38432.000000  38432.000000  38432.000000   
mean      67.500000     15.500000      4.438797      5.293016     31.855099   
std       38.681892      0.500006      2.430033     30.096470     56.853005   
min        1.000000     15.000000      0.000000   -171.780000   -272.730000   
25%       34.000000     15.000000      2.460000     -2.640000     21.270000   
50%       67.500000     15.500000      4.070000      0.130000     25.000000   
75%      101.000000     16.000000      6.230000      3.670000     27.620000   
max      134.000000     16.000000     12.410000    174.180000    394.040000   

               Itmp          Ndir          Pab1          Pab2          Pab3  \
count  38432.000000  38432.000000  38432.000000  38432.000000  38432.000000   
mean      29.578024    152.499078     20.681175     20.670008     20.669003   
std       16.020808    166.933536     35.972707     35.953593     35.952275   
min     -272.730000   -383.080000     -1.990000     -1.990000     -1.990000   
25%       27.100000     18.385000      0.010000      0.010000      0.010000   
50%       30.330000    148.015000      0.030000      0.030000      0.030000   
75%       33.470000    311.450000     21.785000     21.732500     21.697500   
max       45.670000    581.080000     90.880000     90.880000     91.870000   

               Prtv          Patv  
count  38432.000000  38432.000000  
mean     -28.796464    338.350220  
std       50.595720    378.908232  
min     -490.680000     -8.210000  
25%      -56.260000     16.350000  
50%      -12.285000    186.710000  
75%       -0.300000    545.870000  
max      104.150000   1520.860000

In [8]:
np.unique(test_y['Day'])

array([15, 16])

In [9]:
np.unique(test_y['TurbID'])

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134])